name: Branches

on:
  push:
    branches-ignore: ['main']

env:
  FORCE_COLOR: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: ${{ github.workflow }}
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --child-concurrency=10
      - name: Types
        run: pnpm turbo types
      - name: Bootstrap Database
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/test_db
        run: pnpm --filter confetti-db-bootstrapper run bootstrap
      - name: Check
        run: pnpm check:ci
      - name: Test
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/test_db
        run: pnpm test:ci
